import './globals.css';
import type { Metadata } from 'next';
import { AuthProvider } from '@/components/providers/SessionProvider';
import Provider from '@/components/providers/Provider';
import { cardo, arial } from '@/fonts/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${cardo.variable} ${arial.variable}`}>
        <AuthProvider>
          <Provider>{children}</Provider>
        </AuthProvider>
      </body>
    </html>
  );
}
